layout_spectrum: 0.9360902
color:
  saturation: 0.689044
  brandStrength: 0.5859292
  lightness: 0.4709989
  brandColors:
    - '#FFFFFC'
    - '#1E3027'
    - '#9A664A'
    - '#FFCE9B'
    - '#5C9A77'
  rhythmicContrast: 0.4924812
typography_spectrum: 0.820086
name: Kevin Marcheschi Professional  Angler
